# Use an official Python runtime as a parent image
FROM python:3.7-slim

# Set the working directory in the container to /CS342ReviewAnalyzer-master
WORKDIR /CS342ReviewAnalyzer-master

# Add metadata to an image
LABEL maintainer="yourname@example.com" \
      version="1.0"


# Install any needed packages specified in requirements.txt
ADD requirements.txt requirements.txt
RUN pip install --no-cache-dir -r requirements.txt

# Copy the current directory contents into the container at /app
ADD ./CS342ReviewAnalyzer-master


# Make port 80 available to the world outside this container
EXPOSE 80

# Run main.py when the container launches
CMD ["python3", "run", "src/main.py"]

